#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
OUTPUT_PATH="${GENERATED_CLIENT_OUTPUT_PATH:-$ROOT_DIR/packages/contracts/generated/client.ts}"
TYPES_INPUT_PATH="${GENERATED_TYPES_INPUT_PATH:-$ROOT_DIR/packages/contracts/generated/types.ts}"

if [[ ! -f "$TYPES_INPUT_PATH" ]]; then
  echo "Missing generated TypeScript types: $TYPES_INPUT_PATH" >&2
  echo "Run 'pnpm generate:types' first." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" <<'EOF'
// Generated by packages/contracts/scripts/generate-client.sh. Do not edit by hand.
import createClient, { type ClientOptions } from "openapi-fetch";

import type { paths } from "./types";

export type ContractsClient = ReturnType<typeof createContractsClient>;
export type ContractsClientOptions = ClientOptions;

export function createContractsClient(options: ContractsClientOptions = {}) {
  return createClient<paths>(options);
}
EOF

echo "Wrote generated client to $OUTPUT_PATH"
