// abstract: Shared constants and defaults for the deck.gl-backed taxonomy leaf renderer.
// out_of_scope: Query orchestration and scene-layer instantiation.

export const LEAF_POINT_TITLE_ACTIVATION_ZOOM = 0.85;
export const LEAF_POINT_TITLE_FADE_START_ZOOM =
  LEAF_POINT_TITLE_ACTIVATION_ZOOM - 0.35;
export const LEAF_POINT_TITLE_FADE_END_ZOOM =
  LEAF_POINT_TITLE_ACTIVATION_ZOOM + 0.05;
export const LEAF_INITIAL_POINT_TITLE_ZOOM =
  LEAF_POINT_TITLE_ACTIVATION_ZOOM + 0.01;
export const LEAF_HYDRATION_OVERSCAN = 320;
export const LEAF_LAYOUT_TILE_SIZE = 2048;
export const LEAF_VIEWPORT_SNAPSHOT_INTERVAL_MS = 48;
export const LEAF_ZOOM_CONTROL_MIN_PERCENT = 25;
export const LEAF_ZOOM_CONTROL_MAX_PERCENT = 400;
export const LEAF_ZOOM_CONTROL_SNAP_PERCENTS = [25, 50, 100, 200, 400] as const;

export const LEAF_POINT_COLOR_RGB = [120, 163, 243] as const;
export const LEAF_POINT_OUTER_OPACITY = 0.68;
export const LEAF_POINT_INNER_OPACITY = 0.96;
export const LEAF_POINT_DIMMED_OPACITY = 0.28;
export const LEAF_POINT_HOVER_OPACITY = 1;
export const LEAF_EDGE_BASE_OPACITY = 0.2;
export const LEAF_EDGE_DIMMED_OPACITY = 0.22;
export const LEAF_EDGE_ACTIVE_OPACITY = 0.88;
export const LEAF_TITLE_LABEL_BASE_ALPHA = 232;
export const LEAF_TITLE_LABEL_FONT_SIZE_PX = 24;
export const LEAF_TITLE_LABEL_LINE_HEIGHT = 1.25;
export const LEAF_TITLE_LABEL_PIXEL_OFFSET_Y = 16;
export const LEAF_TITLE_LABEL_MAX_WIDTH_EM = 16;
export const LEAF_TITLE_LABEL_COLLISION_AVERAGE_CHAR_WIDTH_EM = 0.54;
export const LEAF_TITLE_LABEL_COLLISION_MIN_WIDTH_EM = 2;
export const LEAF_TITLE_LABEL_COLLISION_PADDING_PX = 6;
