"""add job queue webhook events

Revision ID: e3e23610d7e1
Revises: 8a6f3c2d9b10
Create Date: 2026-04-25 14:11:14.665702

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3e23610d7e1"
down_revision: str | Sequence[str] | None = "8a6f3c2d9b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_queue_webhook_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("queue_name", sa.Text(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.Column("terminal_state", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_queue_webhook_events")),
        sa.UniqueConstraint("event_id", name="uq_job_queue_webhook_events_event_id"),
    )
    op.create_index(
        "ix_job_queue_webhook_events_pending",
        "job_queue_webhook_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "job_queue_webhook_wakeups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["job_queue_webhook_events.event_id"],
            name=op.f("fk_job_queue_webhook_wakeups_event_id_job_queue_webhook_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_queue_webhook_wakeups")),
        sa.UniqueConstraint("event_id", name="uq_job_queue_webhook_wakeups_event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_queue_webhook_wakeups")
    op.drop_index("ix_job_queue_webhook_events_pending", table_name="job_queue_webhook_events")
    op.drop_table("job_queue_webhook_events")
    # ### end Alembic commands ###
