"""replace card review jobs with candidates

Revision ID: 5f0c4c7f1e2a
Revises: ff19bce112ef
Create Date: 2026-04-24 11:43:51.114662

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f0c4c7f1e2a"
down_revision: str | Sequence[str] | None = "ff19bce112ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workflow_unit_id", sa.Integer(), nullable=False),
        sa.Column("parent_candidate_id", sa.Integer(), nullable=True),
        sa.Column("card_payload", sa.JSON(), nullable=False),
        sa.Column("origin_step", sa.Text(), nullable=False),
        sa.Column("origin_job_id", sa.Integer(), nullable=False),
        sa.Column("origin_ordinal", sa.Integer(), nullable=False),
        sa.Column("review_job_id", sa.Integer(), nullable=True),
        sa.Column("repair_job_id", sa.Integer(), nullable=True),
        sa.Column(
            "ingestion_handoff_done", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_candidate_id"],
            ["card_candidates.id"],
            name=op.f("fk_card_candidates_parent_candidate_id_card_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_unit_id"],
            ["workflow_units.id"],
            name=op.f("fk_card_candidates_workflow_unit_id_workflow_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_candidates")),
        sa.UniqueConstraint(
            "parent_candidate_id",
            "origin_step",
            "origin_job_id",
            "origin_ordinal",
            name="uq_card_candidates_parent_origin",
        ),
        sa.UniqueConstraint(
            "workflow_unit_id",
            "origin_step",
            "origin_job_id",
            "origin_ordinal",
            name="uq_card_candidates_workflow_origin",
        ),
    )
    op.drop_table("card_review_jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_review_jobs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("workflow_unit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ordinal", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("job_queue_job_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "handoff_done",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_unit_id"],
            ["workflow_units.id"],
            name=op.f("fk_card_review_jobs_workflow_unit_id_workflow_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_review_jobs")),
    )
    op.drop_table("card_candidates")
    # ### end Alembic commands ###
