"""
Abstract: Alembic baseline for current source-pipeline persistence schema.
Out of scope: Runtime orchestration behavior and queue transport.

initial_source_pipeline_schema

Revision ID: 450213902113
Revises:
Create Date: 2026-04-29 14:21:36.135252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "450213902113"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_queue_webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("queue_name", sa.Text(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.Column("terminal_state", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_queue_webhook_events")),
        sa.UniqueConstraint("event_id", name="uq_job_queue_webhook_events_event_id"),
    )
    op.create_index(
        "ix_job_queue_webhook_events_pending",
        "job_queue_webhook_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.Text(), nullable=False),
        sa.Column("config_payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    op.create_table(
        "job_queue_webhook_wakeups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["job_queue_webhook_events.event_id"],
            name=op.f("fk_job_queue_webhook_wakeups_event_id_job_queue_webhook_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_queue_webhook_wakeups")),
        sa.UniqueConstraint("event_id", name="uq_job_queue_webhook_wakeups_event_id"),
    )
    op.create_table(
        "workflow_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("page_to_card_job_id", sa.Integer(), nullable=True),
        sa.Column("page_to_card_terminal_state", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_workflow_units_workflow_run_id_workflow_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_units")),
    )
    op.create_table(
        "card_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_unit_id", sa.Integer(), nullable=False),
        sa.Column("parent_candidate_id", sa.Integer(), nullable=True),
        sa.Column("card_payload", sa.JSON(), nullable=False),
        sa.Column("origin_step", sa.Text(), nullable=False),
        sa.Column("origin_job_id", sa.Integer(), nullable=False),
        sa.Column("origin_ordinal", sa.Integer(), nullable=False),
        sa.Column("review_job_id", sa.Integer(), nullable=True),
        sa.Column("review_terminal_state", sa.Text(), nullable=True),
        sa.Column("repair_job_id", sa.Integer(), nullable=True),
        sa.Column("repair_terminal_state", sa.Text(), nullable=True),
        sa.Column(
            "ingestion_handoff_done", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_candidate_id"],
            ["card_candidates.id"],
            name=op.f("fk_card_candidates_parent_candidate_id_card_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_unit_id"],
            ["workflow_units.id"],
            name=op.f("fk_card_candidates_workflow_unit_id_workflow_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_candidates")),
        sa.UniqueConstraint(
            "parent_candidate_id",
            "origin_step",
            "origin_job_id",
            "origin_ordinal",
            name="uq_card_candidates_parent_origin",
        ),
        sa.UniqueConstraint(
            "workflow_unit_id",
            "origin_step",
            "origin_job_id",
            "origin_ordinal",
            name="uq_card_candidates_workflow_origin",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_candidates")
    op.drop_table("workflow_units")
    op.drop_table("job_queue_webhook_wakeups")
    op.drop_table("workflow_runs")
    op.drop_index("ix_job_queue_webhook_events_pending", table_name="job_queue_webhook_events")
    op.drop_table("job_queue_webhook_events")
    # ### end Alembic commands ###
