// abstract: Complete test env factory for web BFF runtime configuration.
// out_of_scope: Browser runtime env and external service behavior.

import type { WebServerEnv } from "../config.js";

export function createWebServerTestEnv(
  overrides: WebServerEnv = {},
): WebServerEnv {
  return {
    KNOWLEDGE_WEB_ANON_BURST_LIMIT: "20",
    KNOWLEDGE_WEB_ANON_BURST_WINDOW_SECONDS: "60",
    KNOWLEDGE_WEB_ANON_TOTAL_LIMIT: "200",
    KNOWLEDGE_WEB_ANON_TOTAL_WINDOW_SECONDS: "86400",
    KNOWLEDGE_WEB_AUTH_BURST_LIMIT: "120",
    KNOWLEDGE_WEB_AUTH_BURST_WINDOW_SECONDS: "60",
    KNOWLEDGE_WEB_AUTH_TOTAL_LIMIT: "2000",
    KNOWLEDGE_WEB_AUTH_TOTAL_WINDOW_SECONDS: "86400",
    KNOWLEDGE_API_SEARCH_MAX_CONNECTED: "20",
    KNOWLEDGE_API_SEARCH_MAX_MATCHED: "6",
    KNOWLEDGE_WEB_COOKIE_SECURE: "false",
    KNOWLEDGE_WEB_INTERNAL_API_BASE_URL: "http://api:8000",
    KNOWLEDGE_WEB_IP_BURST_LIMIT: "240",
    KNOWLEDGE_WEB_IP_BURST_WINDOW_SECONDS: "60",
    KNOWLEDGE_WEB_IP_TOTAL_LIMIT: "5000",
    KNOWLEDGE_WEB_IP_TOTAL_WINDOW_SECONDS: "86400",
    KNOWLEDGE_WEB_LOGTO_APP_ID: "test-app",
    KNOWLEDGE_WEB_LOGTO_APP_SECRET: "test-secret",
    KNOWLEDGE_WEB_LOGTO_ENDPOINT: "http://logto:3001",
    KNOWLEDGE_WEB_LOGTO_MANAGEMENT_API_BASE_URL: "http://logto:3001/api",
    KNOWLEDGE_WEB_LOGTO_MANAGEMENT_CLIENT_ID: "management-client",
    KNOWLEDGE_WEB_LOGTO_MANAGEMENT_CLIENT_SECRET: "management-secret",
    KNOWLEDGE_WEB_LOGTO_MANAGEMENT_RESOURCE: "https://default.logto.app/api",
    KNOWLEDGE_WEB_LOGTO_MANAGEMENT_SCOPES:
      "read:users create:users update:users delete:users",
    KNOWLEDGE_WEB_LOGTO_MANAGEMENT_TOKEN_URL: "http://logto:3001/oidc/token",
    KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_BASE_URL: "http://mcp:8001",
    KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_CLIENT_ID: "usage-client",
    KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_CLIENT_SECRET: "usage-secret",
    KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_RESOURCE: "https://knowledge-mcp.internal",
    KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_SCOPES: "usage:read",
    KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_TOKEN_URL: "http://logto:3001/oidc/token",
    KNOWLEDGE_WEB_MCP_PUBLIC_BASE_URL: "http://localhost:8002/mcp",
    KNOWLEDGE_WEB_PAT_FINGERPRINT_SECRET:
      "test-pat-fingerprint-secret-with-enough-length",
    KNOWLEDGE_WEB_PUBLIC_BASE_URL: "http://localhost:5173",
    KNOWLEDGE_WEB_QUOTA_REDIS_PREFIX: "knowledge:web:quota:",
    KNOWLEDGE_WEB_REDIS_URL: "redis://redis:6379/0",
    KNOWLEDGE_WEB_SESSION_SECRET: "test-session-secret-with-enough-length",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_BURST_LIMIT: "60",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_BURST_WINDOW_SECONDS: "60",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_TOTAL_LIMIT: "600",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_TOTAL_WINDOW_SECONDS: "86400",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_BURST_LIMIT: "240",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_BURST_WINDOW_SECONDS: "60",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_TOTAL_LIMIT: "5000",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_TOTAL_WINDOW_SECONDS: "86400",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_BURST_LIMIT: "600",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_BURST_WINDOW_SECONDS: "60",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_TOTAL_LIMIT: "15000",
    KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_TOTAL_WINDOW_SECONDS: "86400",
    ...overrides,
  };
}
