#!/usr/bin/env bash
# abstract: Materialize service-scoped container environment files from operator configuration.
# out_of_scope: Secret creation, container lifecycle execution, and application-level defaults.

set -euo pipefail

RUNTIME_ENV_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNTIME_ENV_GENERATED_DIR="$RUNTIME_ENV_ROOT_DIR/infra/env/generated"

runtime_env_value_may_be_empty() {
  case "$1" in
    KNOWLEDGE_LOGTO_DATABASE_STATEMENT_TIMEOUT | \
      KNOWLEDGE_LOGTO_EXTRA_CA_CERT_PATH | \
      KNOWLEDGE_WEB_COOKIE_DOMAIN | \
      KNOWLEDGE_WEB_LOGTO_INTERNAL_ENDPOINT)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

read_runtime_env_value() {
  local resolved_env="$1"
  local name="$2"

  awk -v name="$name" '
    index($0, name "=") == 1 {
      print substr($0, length(name) + 2)
      found = 1
      exit
    }
    END {
      if (!found) {
        exit 1
      }
    }
  ' "$resolved_env"
}

require_runtime_env_value() {
  local resolved_env="$1"
  local name="$2"
  local value

  if ! value="$(read_runtime_env_value "$resolved_env" "$name")"; then
    printf 'Missing required runtime environment variable: %s\n' "$name" >&2
    return 1
  fi
  if [[ -z "$value" ]] && ! runtime_env_value_may_be_empty "$name"; then
    printf 'Missing required runtime environment variable: %s\n' "$name" >&2
    return 1
  fi

  printf '%s' "$value"
}

write_runtime_projection() {
  local resolved_env="$1"
  local output_file="$2"
  shift 2

  local mapping
  local source_name
  local target_name
  local value

  {
    printf '# Generated by scripts/lib/runtime-env.sh. Do not edit.\n'
    for mapping in "$@"; do
      if [[ "$mapping" == *=* ]]; then
        target_name="${mapping%%=*}"
        source_name="${mapping#*=}"
      else
        target_name="$mapping"
        source_name="$mapping"
      fi
      value="$(require_runtime_env_value "$resolved_env" "$source_name")"
      printf '%s=%s\n' "$target_name" "$value"
    done
  } >"$output_file"
  chmod 600 "$output_file"
}

append_derived_runtime_value() {
  local resolved_env="$1"
  local name="$2"
  local value="$3"

  printf '%s=%s\n' "$name" "$value" >>"$resolved_env"
}

runtime_database_url() {
  local resolved_env="$1"
  local scheme="$2"
  local user_name="$3"
  local password_name="$4"
  local host="$5"
  local database_name="$6"
  local user
  local password
  local database

  user="$(require_runtime_env_value "$resolved_env" "$user_name")"
  password="$(require_runtime_env_value "$resolved_env" "$password_name")"
  database="$(require_runtime_env_value "$resolved_env" "$database_name")"
  printf '%s://%s:%s@%s:5432/%s' "$scheme" "$user" "$password" "$host" "$database"
}

write_database_projections() {
  local mode="$1"
  local resolved_env="$2"
  local stage_dir="$3"

  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.postgres.runtime" \
    "POSTGRES_DB=KNOWLEDGE_API_POSTGRES_DB" \
    "POSTGRES_USER=KNOWLEDGE_API_POSTGRES_USER" \
    "POSTGRES_PASSWORD=KNOWLEDGE_API_POSTGRES_PASSWORD" \
    "APP_DB_USER=KNOWLEDGE_API_DB_USER" \
    "APP_DB_PASSWORD=KNOWLEDGE_API_DB_PASSWORD" \
    "MIGRATION_DB_USER=KNOWLEDGE_API_MIGRATION_DB_USER" \
    "MIGRATION_DB_PASSWORD=KNOWLEDGE_API_MIGRATION_DB_PASSWORD"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.knowledge-corpus-db.runtime" \
    "POSTGRES_DB=KNOWLEDGE_CORPUS_POSTGRES_DB" \
    "POSTGRES_USER=KNOWLEDGE_CORPUS_POSTGRES_USER" \
    "POSTGRES_PASSWORD=KNOWLEDGE_CORPUS_POSTGRES_PASSWORD" \
    "APP_DB_USER=KNOWLEDGE_CORPUS_APP_DB_USER" \
    "APP_DB_PASSWORD=KNOWLEDGE_CORPUS_APP_DB_PASSWORD" \
    "MIGRATION_DB_USER=KNOWLEDGE_CORPUS_MIGRATION_DB_USER" \
    "MIGRATION_DB_PASSWORD=KNOWLEDGE_CORPUS_MIGRATION_DB_PASSWORD"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.source-pipeline-db.runtime" \
    "POSTGRES_DB=SOURCE_PIPELINE_POSTGRES_DB" \
    "POSTGRES_USER=SOURCE_PIPELINE_POSTGRES_USER" \
    "POSTGRES_PASSWORD=SOURCE_PIPELINE_POSTGRES_PASSWORD" \
    "APP_DB_USER=SOURCE_PIPELINE_APP_DB_USER" \
    "APP_DB_PASSWORD=SOURCE_PIPELINE_APP_DB_PASSWORD" \
    "MIGRATION_DB_USER=SOURCE_PIPELINE_MIGRATION_DB_USER" \
    "MIGRATION_DB_PASSWORD=SOURCE_PIPELINE_MIGRATION_DB_PASSWORD"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.mcp-db.runtime" \
    "POSTGRES_DB=KNOWLEDGE_MCP_POSTGRES_DB" \
    "POSTGRES_USER=KNOWLEDGE_MCP_POSTGRES_USER" \
    "POSTGRES_PASSWORD=KNOWLEDGE_MCP_POSTGRES_PASSWORD" \
    "APP_DB_USER=KNOWLEDGE_MCP_DB_USER" \
    "APP_DB_PASSWORD=KNOWLEDGE_MCP_DB_PASSWORD" \
    "MIGRATION_DB_USER=KNOWLEDGE_MCP_MIGRATION_DB_USER" \
    "MIGRATION_DB_PASSWORD=KNOWLEDGE_MCP_MIGRATION_DB_PASSWORD"
}

write_application_projections() {
  local mode="$1"
  local resolved_env="$2"
  local stage_dir="$3"

  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.api-migrate.runtime" \
    "KNOWLEDGE_API_MIGRATION_DATABASE_URL"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.knowledge-corpus-migrate.runtime" \
    "KNOWLEDGE_CORPUS_DATABASE_URL" \
    "KNOWLEDGE_CORPUS_MIGRATION_DATABASE_URL"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.source-pipeline-migrate.runtime" \
    "SOURCE_PIPELINE_MIGRATION_DATABASE_URL"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.mcp-migrate.runtime" \
    "KNOWLEDGE_MCP_DATABASE_URL" \
    "KNOWLEDGE_MCP_MIGRATION_DATABASE_URL"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.api-worker.runtime" \
    "KNOWLEDGE_API_DATABASE_URL" \
    "KNOWLEDGE_API_REDIS_URL" \
    "KNOWLEDGE_API_EMBEDDING_API_URL" \
    "KNOWLEDGE_API_EMBEDDING_MODEL" \
    "KNOWLEDGE_API_EMBEDDING_API_KEY" \
    "KNOWLEDGE_API_EMBEDDING_TIMEOUT_SECONDS" \
    "KNOWLEDGE_API_SEARCH_MAX_MATCHED" \
    "KNOWLEDGE_API_SEARCH_MAX_CONNECTED" \
    "KNOWLEDGE_API_SEARCH_VECTOR_CANDIDATE_POOL_SIZE" \
    "KNOWLEDGE_API_SEARCH_RESPONSE_CACHE_TTL_SECONDS" \
    "KNOWLEDGE_API_SEARCH_EMBEDDING_CACHE_TTL_SECONDS" \
    "KNOWLEDGE_API_TAXONOMY_VIEW_CACHE_TTL_SECONDS" \
    "KNOWLEDGE_API_EDGE_TITLE_MENTION_TOP_K" \
    "KNOWLEDGE_API_EDGE_SEMANTIC_TOP_K" \
    "KNOWLEDGE_API_EDGE_SEMANTIC_MIN_STRENGTH" \
    "KNOWLEDGE_API_EDGE_SEMANTIC_CANDIDATE_LIMIT" \
    "KNOWLEDGE_API_LOG_LEVEL" \
    "KNOWLEDGE_API_LOG_FILE_PATH" \
    "KNOWLEDGE_API_LOG_FILE_MAX_BYTES" \
    "KNOWLEDGE_API_LOG_FILE_BACKUP_COUNT" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_CURSOR_COMMAND" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_CURSOR_WORKSPACE_ROOT" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_CURSOR_TIMEOUT_SECONDS" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_CURSOR_MAX_RETRIES" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_MAX_WORKERS"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.mcp.runtime" \
    "KNOWLEDGE_MCP_PUBLIC_BASE_URL" \
    "KNOWLEDGE_MCP_INTERNAL_API_BASE_URL" \
    "KNOWLEDGE_MCP_REDIS_URL" \
    "KNOWLEDGE_MCP_DATABASE_URL" \
    "KNOWLEDGE_MCP_LOGTO_ISSUER" \
    "KNOWLEDGE_MCP_LOGTO_DISCOVERY_URL" \
    "KNOWLEDGE_MCP_LOGTO_TOKEN_URL" \
    "KNOWLEDGE_MCP_LOGTO_RESOURCE" \
    "KNOWLEDGE_MCP_LOGTO_REQUIRED_SCOPES" \
    "KNOWLEDGE_MCP_LOGTO_TOKEN_EXCHANGE_CLIENT_ID" \
    "KNOWLEDGE_MCP_LOGTO_TOKEN_EXCHANGE_CLIENT_SECRET" \
    "KNOWLEDGE_MCP_PAT_FINGERPRINT_SECRET" \
    "KNOWLEDGE_MCP_USAGE_SUMMARY_AUTH_RESOURCE" \
    "KNOWLEDGE_MCP_USAGE_SUMMARY_REQUIRED_SCOPE" \
    "KNOWLEDGE_MCP_USAGE_SUMMARY_ALLOWED_CLIENT_ID" \
    "KNOWLEDGE_MCP_USAGE_SUMMARY_MAX_BATCH_SIZE" \
    "KNOWLEDGE_MCP_ALLOWED_ORIGINS" \
    "KNOWLEDGE_MCP_TOKEN_CACHE_TTL_SECONDS" \
    "KNOWLEDGE_MCP_AUTH_HTTP_TIMEOUT_SECONDS" \
    "KNOWLEDGE_MCP_QUOTA_REDIS_PREFIX" \
    "KNOWLEDGE_MCP_USER_DAILY_LIMIT" \
    "KNOWLEDGE_MCP_USER_DAILY_WINDOW_SECONDS" \
    "KNOWLEDGE_MCP_USER_WEEKLY_LIMIT" \
    "KNOWLEDGE_MCP_USER_WEEKLY_WINDOW_SECONDS"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.taxonomy-view-layout.runtime" \
    "KNOWLEDGE_API_DATABASE_URL" \
    "KNOWLEDGE_API_REDIS_URL" \
    "KNOWLEDGE_API_TAXONOMY_VIEW_CACHE_TTL_SECONDS" \
    "KNOWLEDGE_API_EDGE_TITLE_MENTION_TOP_K" \
    "KNOWLEDGE_API_EDGE_SEMANTIC_TOP_K" \
    "KNOWLEDGE_API_EDGE_SEMANTIC_MIN_STRENGTH" \
    "KNOWLEDGE_API_EDGE_SEMANTIC_CANDIDATE_LIMIT"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.taxonomy-classification.runtime" \
    "KNOWLEDGE_API_DATABASE_URL" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_QUEUE_NAME" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_JOB_QUEUE_BASE_URL" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_JOB_QUEUE_TOKEN_URL" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_JOB_QUEUE_CLIENT_ID" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_JOB_QUEUE_CLIENT_SECRET" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_JOB_QUEUE_RESOURCE" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_JOB_QUEUE_SCOPES" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_POLL_INTERVAL_SECONDS" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_POLL_BATCH_SIZE" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_RECONCILE_INTERVAL_SECONDS" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_RECONCILE_BATCH_SIZE" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_CONTINUATION_REQUEST_BATCH_SIZE" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_CONTINUATION_FLUSH_INTERVAL_SECONDS" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_PROJECTION_REFRESH_BATCH_SIZE"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.taxonomy-classification-webhook.runtime" \
    "KNOWLEDGE_API_DATABASE_URL" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_QUEUE_NAME" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_WEBHOOK_AUTH_ISSUER" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_WEBHOOK_AUTH_RESOURCE" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_WEBHOOK_AUTH_DISCOVERY_URL" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_WEBHOOK_ALLOWED_CLIENT_ID" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_WEBHOOK_AUTH_HTTP_TIMEOUT_SECONDS" \
    "KNOWLEDGE_API_TAXONOMY_CLASSIFICATION_WEBHOOK_PUBLIC_PATH"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.source-pipeline-orchestrator.runtime" \
    "SOURCE_PIPELINE_DATABASE_URL" \
    "SOURCE_PIPELINE_KNOWLEDGE_API_BASE_URL" \
    "SOURCE_PIPELINE_JOB_QUEUE_BASE_URL" \
    "SOURCE_PIPELINE_JOB_QUEUE_TOKEN_URL" \
    "SOURCE_PIPELINE_JOB_QUEUE_CLIENT_ID" \
    "SOURCE_PIPELINE_JOB_QUEUE_CLIENT_SECRET" \
    "SOURCE_PIPELINE_JOB_QUEUE_RESOURCE" \
    "SOURCE_PIPELINE_JOB_QUEUE_SCOPES" \
    "SOURCE_PIPELINE_POLL_INTERVAL_SECONDS" \
    "SOURCE_PIPELINE_POLL_BATCH_SIZE" \
    "SOURCE_PIPELINE_RECONCILE_INTERVAL_SECONDS" \
    "SOURCE_PIPELINE_RECONCILE_BATCH_SIZE"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.source-pipeline-webhook.runtime" \
    "SOURCE_PIPELINE_DATABASE_URL" \
    "SOURCE_PIPELINE_WEBHOOK_AUTH_ISSUER" \
    "SOURCE_PIPELINE_WEBHOOK_AUTH_RESOURCE" \
    "SOURCE_PIPELINE_WEBHOOK_AUTH_DISCOVERY_URL" \
    "SOURCE_PIPELINE_WEBHOOK_ALLOWED_CLIENT_ID" \
    "SOURCE_PIPELINE_WEBHOOK_AUTH_HTTP_TIMEOUT_SECONDS" \
    "SOURCE_PIPELINE_WEBHOOK_PUBLIC_PATH"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.web.runtime" \
    "KNOWLEDGE_WEB_PUBLIC_BASE_URL" \
    "KNOWLEDGE_WEB_MCP_PUBLIC_BASE_URL" \
    "KNOWLEDGE_WEB_INTERNAL_API_BASE_URL" \
    "KNOWLEDGE_API_SEARCH_MAX_MATCHED" \
    "KNOWLEDGE_API_SEARCH_MAX_CONNECTED" \
    "KNOWLEDGE_WEB_REDIS_URL" \
    "KNOWLEDGE_WEB_SESSION_SECRET" \
    "KNOWLEDGE_WEB_COOKIE_SECURE" \
    "KNOWLEDGE_WEB_COOKIE_DOMAIN" \
    "KNOWLEDGE_WEB_TRUST_PROXY" \
    "KNOWLEDGE_WEB_LOGTO_ENDPOINT" \
    "KNOWLEDGE_WEB_LOGTO_INTERNAL_ENDPOINT" \
    "KNOWLEDGE_WEB_LOGTO_APP_ID" \
    "KNOWLEDGE_WEB_LOGTO_APP_SECRET" \
    "KNOWLEDGE_WEB_LOGTO_MANAGEMENT_API_BASE_URL" \
    "KNOWLEDGE_WEB_LOGTO_MANAGEMENT_TOKEN_URL" \
    "KNOWLEDGE_WEB_LOGTO_MANAGEMENT_RESOURCE" \
    "KNOWLEDGE_WEB_LOGTO_MANAGEMENT_SCOPES" \
    "KNOWLEDGE_WEB_LOGTO_MANAGEMENT_CLIENT_ID" \
    "KNOWLEDGE_WEB_LOGTO_MANAGEMENT_CLIENT_SECRET" \
    "KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_BASE_URL" \
    "KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_TOKEN_URL" \
    "KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_RESOURCE" \
    "KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_SCOPES" \
    "KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_CLIENT_ID" \
    "KNOWLEDGE_WEB_MCP_USAGE_SUMMARY_CLIENT_SECRET" \
    "KNOWLEDGE_WEB_PAT_FINGERPRINT_SECRET" \
    "KNOWLEDGE_WEB_QUOTA_REDIS_PREFIX" \
    "KNOWLEDGE_WEB_ANON_BURST_LIMIT" \
    "KNOWLEDGE_WEB_ANON_BURST_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_ANON_TOTAL_LIMIT" \
    "KNOWLEDGE_WEB_ANON_TOTAL_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_AUTH_BURST_LIMIT" \
    "KNOWLEDGE_WEB_AUTH_BURST_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_AUTH_TOTAL_LIMIT" \
    "KNOWLEDGE_WEB_AUTH_TOTAL_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_IP_BURST_LIMIT" \
    "KNOWLEDGE_WEB_IP_BURST_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_IP_TOTAL_LIMIT" \
    "KNOWLEDGE_WEB_IP_TOTAL_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_BURST_LIMIT" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_BURST_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_TOTAL_LIMIT" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_ANON_TOTAL_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_BURST_LIMIT" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_BURST_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_TOTAL_LIMIT" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_AUTH_TOTAL_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_BURST_LIMIT" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_BURST_WINDOW_SECONDS" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_TOTAL_LIMIT" \
    "KNOWLEDGE_WEB_TAXONOMY_VIEW_IP_TOTAL_WINDOW_SECONDS"
}

write_logto_projections() {
  local mode="$1"
  local resolved_env="$2"
  local stage_dir="$3"
  local logto_database_url

  logto_database_url="$(runtime_database_url \
    "$resolved_env" \
    "postgres" \
    "KNOWLEDGE_LOGTO_POSTGRES_USER" \
    "KNOWLEDGE_LOGTO_POSTGRES_PASSWORD" \
    "logto-postgres" \
    "KNOWLEDGE_LOGTO_POSTGRES_DB")"
  append_derived_runtime_value "$resolved_env" RUNTIME_LOGTO_DATABASE_URL "$logto_database_url"

  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.logto-postgres.runtime" \
    "POSTGRES_DB=KNOWLEDGE_LOGTO_POSTGRES_DB" \
    "POSTGRES_USER=KNOWLEDGE_LOGTO_POSTGRES_USER" \
    "POSTGRES_PASSWORD=KNOWLEDGE_LOGTO_POSTGRES_PASSWORD"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.$mode.logto.runtime" \
    "DB_URL=RUNTIME_LOGTO_DATABASE_URL" \
    "ENDPOINT=KNOWLEDGE_LOGTO_ENDPOINT" \
    "ADMIN_ENDPOINT=KNOWLEDGE_LOGTO_ADMIN_ENDPOINT" \
    "TRUST_PROXY_HEADER=KNOWLEDGE_LOGTO_TRUST_PROXY_HEADER" \
    "DATABASE_STATEMENT_TIMEOUT=KNOWLEDGE_LOGTO_DATABASE_STATEMENT_TIMEOUT"
}

write_test_migration_projections() {
  local resolved_env="$1"
  local stage_dir="$2"

  append_derived_runtime_value \
    "$resolved_env" \
    RUNTIME_TEST_KNOWLEDGE_CORPUS_DATABASE_URL \
    "$(runtime_database_url "$resolved_env" postgresql+psycopg KNOWLEDGE_CORPUS_APP_DB_USER KNOWLEDGE_CORPUS_APP_DB_PASSWORD knowledge_corpus_db KNOWLEDGE_CORPUS_POSTGRES_DB)"
  append_derived_runtime_value \
    "$resolved_env" \
    RUNTIME_TEST_KNOWLEDGE_CORPUS_MIGRATION_DATABASE_URL \
    "$(runtime_database_url "$resolved_env" postgresql+psycopg KNOWLEDGE_CORPUS_MIGRATION_DB_USER KNOWLEDGE_CORPUS_MIGRATION_DB_PASSWORD knowledge_corpus_db KNOWLEDGE_CORPUS_POSTGRES_DB)"
  append_derived_runtime_value \
    "$resolved_env" \
    RUNTIME_TEST_SOURCE_PIPELINE_MIGRATION_DATABASE_URL \
    "$(runtime_database_url "$resolved_env" postgresql+psycopg SOURCE_PIPELINE_MIGRATION_DB_USER SOURCE_PIPELINE_MIGRATION_DB_PASSWORD source_pipeline_db SOURCE_PIPELINE_POSTGRES_DB)"
  append_derived_runtime_value \
    "$resolved_env" \
    RUNTIME_TEST_KNOWLEDGE_MCP_DATABASE_URL \
    "$(runtime_database_url "$resolved_env" postgresql+psycopg KNOWLEDGE_MCP_DB_USER KNOWLEDGE_MCP_DB_PASSWORD mcp_db KNOWLEDGE_MCP_POSTGRES_DB)"
  append_derived_runtime_value \
    "$resolved_env" \
    RUNTIME_TEST_KNOWLEDGE_MCP_MIGRATION_DATABASE_URL \
    "$(runtime_database_url "$resolved_env" postgresql+psycopg KNOWLEDGE_MCP_MIGRATION_DB_USER KNOWLEDGE_MCP_MIGRATION_DB_PASSWORD mcp_db KNOWLEDGE_MCP_POSTGRES_DB)"

  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.test.knowledge-corpus-migrate.runtime" \
    "KNOWLEDGE_CORPUS_DATABASE_URL=RUNTIME_TEST_KNOWLEDGE_CORPUS_DATABASE_URL" \
    "KNOWLEDGE_CORPUS_MIGRATION_DATABASE_URL=RUNTIME_TEST_KNOWLEDGE_CORPUS_MIGRATION_DATABASE_URL"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.test.source-pipeline-migrate.runtime" \
    "SOURCE_PIPELINE_MIGRATION_DATABASE_URL=RUNTIME_TEST_SOURCE_PIPELINE_MIGRATION_DATABASE_URL"
  write_runtime_projection \
    "$resolved_env" \
    "$stage_dir/.env.test.mcp-migrate.runtime" \
    "KNOWLEDGE_MCP_DATABASE_URL=RUNTIME_TEST_KNOWLEDGE_MCP_DATABASE_URL" \
    "KNOWLEDGE_MCP_MIGRATION_DATABASE_URL=RUNTIME_TEST_KNOWLEDGE_MCP_MIGRATION_DATABASE_URL"
}

materialize_runtime_env() {
  local mode="$1"
  local operator_env="$2"
  local -a compose_args
  local resolved_env
  local stage_dir
  local staged_path

  if [[ ! -f "$operator_env" ]]; then
    printf 'Environment file does not exist: %s\n' "$operator_env" >&2
    return 1
  fi

  case "$mode" in
    dev)
      compose_args=(
        -f "$RUNTIME_ENV_ROOT_DIR/infra/compose/docker-compose.base.yml"
        -f "$RUNTIME_ENV_ROOT_DIR/infra/compose/docker-compose.dev.yml"
      )
      ;;
    prod)
      compose_args=(
        -f "$RUNTIME_ENV_ROOT_DIR/infra/compose/docker-compose.base.yml"
        -f "$RUNTIME_ENV_ROOT_DIR/infra/compose/docker-compose.prod.yml"
      )
      ;;
    test)
      compose_args=(-f "$RUNTIME_ENV_ROOT_DIR/infra/compose/docker-compose.test.yml")
      ;;
    *)
      printf 'Unsupported runtime environment: %s\n' "$mode" >&2
      return 1
      ;;
  esac

  umask 077
  mkdir -p "$RUNTIME_ENV_GENERATED_DIR"
  chmod 700 "$RUNTIME_ENV_GENERATED_DIR"
  stage_dir="$(mktemp -d "$RUNTIME_ENV_GENERATED_DIR/.$mode.tmp.XXXXXX")"
  resolved_env="$stage_dir/resolved.env"

  if ! (
    set -euo pipefail
    docker compose --env-file "$operator_env" "${compose_args[@]}" config --environment >"$resolved_env"
    chmod 600 "$resolved_env"

    write_database_projections "$mode" "$resolved_env" "$stage_dir"
    if [[ "$mode" == "test" ]]; then
      write_test_migration_projections "$resolved_env" "$stage_dir"
    else
      write_logto_projections "$mode" "$resolved_env" "$stage_dir"
      write_application_projections "$mode" "$resolved_env" "$stage_dir"
    fi

    if [[ "$mode" == "prod" ]]; then
      local ca_source
      ca_source="$(read_runtime_env_value "$resolved_env" KNOWLEDGE_LOGTO_EXTRA_CA_CERT_PATH || true)"
      if [[ -n "$ca_source" && ! -f "$ca_source" ]]; then
        printf 'Logto CA certificate does not exist: %s\n' "$ca_source" >&2
        exit 1
      fi
      if [[ -n "$ca_source" ]]; then
        cp "$ca_source" "$stage_dir/.env.prod.logto-extra-ca.crt"
      else
        : >"$stage_dir/.env.prod.logto-extra-ca.crt"
      fi
      chmod 600 "$stage_dir/.env.prod.logto-extra-ca.crt"
      write_runtime_projection \
        "$resolved_env" \
        "$stage_dir/.env.prod.cloudflare-ingress.runtime" \
        "TUNNEL_TOKEN=CLOUDFLARE_TUNNEL_TOKEN"
    fi
  ); then
    rm -rf "$stage_dir"
    return 1
  fi

  rm -f "$resolved_env"
  for staged_path in "$stage_dir"/.env."$mode".*; do
    [[ -f "$staged_path" ]] || continue
    mv -f "$staged_path" "$RUNTIME_ENV_GENERATED_DIR/"
  done
  rmdir "$stage_dir"
}
