"""
Abstract: Alembic revision for public MCP service persistence changes.
Out of scope: Runtime MCP request handling and quota decision logic.

initial_mcp_usage_events

Revision ID: e37adb479aca
Revises:
Create Date: 2026-04-27 22:40:51.694499

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e37adb479aca"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("user_sub", sa.Text(), nullable=False),
        sa.Column("pat_fingerprint", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("query_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("connected_count", sa.Integer(), nullable=False),
        sa.Column("cost_units", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mcp_search_usage_events_pat_created",
        "search_usage_events",
        ["pat_fingerprint", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_search_usage_events_tool_created",
        "search_usage_events",
        ["tool_name", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_search_usage_events_user_created",
        "search_usage_events",
        ["user_sub", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mcp_search_usage_events_user_created", table_name="search_usage_events")
    op.drop_index("ix_mcp_search_usage_events_tool_created", table_name="search_usage_events")
    op.drop_index("ix_mcp_search_usage_events_pat_created", table_name="search_usage_events")
    op.drop_table("search_usage_events")
    # ### end Alembic commands ###
