"""
Abstract: Alembic revision for public MCP service persistence changes.
Out of scope: Runtime MCP request handling and quota decision logic.

initial_mcp_schema

Revision ID: b513062e763d
Revises:
Create Date: 2026-04-29 14:21:45.300872

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b513062e763d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_search_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_sub", sa.Text(), nullable=False),
        sa.Column("pat_fingerprint", sa.Text(), nullable=False),
        sa.Column("mcp_session_id", sa.Text(), nullable=False),
        sa.Column("raw_query", sa.Text(), nullable=False),
        sa.Column("query_hash", sa.Text(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("connected_count", sa.Integer(), nullable=False),
        sa.Column("matched_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("search_algorithm_version", sa.Integer(), nullable=False),
        sa.Column("exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mcp_agent_search_events_export_pending",
        "agent_search_events",
        ["occurred_at"],
        unique=False,
        postgresql_where=sa.text("exported_at IS NULL"),
    )
    op.create_index(
        "ix_mcp_agent_search_events_pat_occurred",
        "agent_search_events",
        ["pat_fingerprint", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_agent_search_events_query_hash_occurred",
        "agent_search_events",
        ["query_hash", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_agent_search_events_session_occurred",
        "agent_search_events",
        ["mcp_session_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_agent_search_events_user_occurred",
        "agent_search_events",
        ["user_sub", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "search_usage_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("user_sub", sa.Text(), nullable=False),
        sa.Column("pat_fingerprint", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("query_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("connected_count", sa.Integer(), nullable=False),
        sa.Column("cost_units", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mcp_search_usage_events_pat_created",
        "search_usage_events",
        ["pat_fingerprint", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_search_usage_events_tool_created",
        "search_usage_events",
        ["tool_name", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_search_usage_events_user_created",
        "search_usage_events",
        ["user_sub", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mcp_search_usage_events_user_created", table_name="search_usage_events")
    op.drop_index("ix_mcp_search_usage_events_tool_created", table_name="search_usage_events")
    op.drop_index("ix_mcp_search_usage_events_pat_created", table_name="search_usage_events")
    op.drop_table("search_usage_events")
    op.drop_index("ix_mcp_agent_search_events_user_occurred", table_name="agent_search_events")
    op.drop_index("ix_mcp_agent_search_events_session_occurred", table_name="agent_search_events")
    op.drop_index(
        "ix_mcp_agent_search_events_query_hash_occurred", table_name="agent_search_events"
    )
    op.drop_index("ix_mcp_agent_search_events_pat_occurred", table_name="agent_search_events")
    op.drop_index(
        "ix_mcp_agent_search_events_export_pending",
        table_name="agent_search_events",
        postgresql_where=sa.text("exported_at IS NULL"),
    )
    op.drop_table("agent_search_events")
    # ### end Alembic commands ###
