"""add taxonomy classification queue tables

Revision ID: f8a9b0c1d2e3
Revises: 7ced88ef1cab
Create Date: 2026-04-26 18:00:00.000000

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8a9b0c1d2e3"
down_revision: str | Sequence[str] | None = "7ced88ef1cab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_taxonomy_nodes_single_root",
        "taxonomy_nodes",
        [sa.text("(COALESCE(parent_id, 0))")],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "taxonomy_classification_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_node_id", sa.Integer(), nullable=False),
        sa.Column("source_unclassified_node_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("terminal_state", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_payload", sa.JSON(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_taxonomy_classification_jobs_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_classification_jobs_scope_node_id_taxonomy_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["source_unclassified_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_classification_jobs_source_unclassified_node_id_taxonomy_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_classification_jobs")),
        sa.UniqueConstraint("job_id", name="uq_taxonomy_classification_jobs_job_id"),
    )
    op.create_index(
        "uq_taxonomy_classification_jobs_active_scope_source_node",
        "taxonomy_classification_jobs",
        ["scope_node_id", "source_unclassified_node_id", "node_id"],
        unique=True,
        postgresql_where=sa.text("processed_at IS NULL AND terminal_state IS NULL"),
    )
    op.create_table(
        "taxonomy_classification_webhook_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("queue_name", sa.Text(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.Column("terminal_state", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_classification_webhook_events")),
        sa.UniqueConstraint(
            "event_id",
            name="uq_taxonomy_classification_webhook_events_event_id",
        ),
    )
    op.create_index(
        "ix_taxonomy_classification_webhook_events_pending",
        "taxonomy_classification_webhook_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "taxonomy_classification_webhook_wakeups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["taxonomy_classification_webhook_events.event_id"],
            name=op.f(
                "fk_taxonomy_classification_webhook_wakeups_event_id_"
                "taxonomy_classification_webhook_events"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_classification_webhook_wakeups")),
        sa.UniqueConstraint(
            "event_id",
            name="uq_taxonomy_classification_webhook_wakeups_event_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taxonomy_classification_webhook_wakeups")
    op.drop_index(
        "ix_taxonomy_classification_webhook_events_pending",
        table_name="taxonomy_classification_webhook_events",
    )
    op.drop_table("taxonomy_classification_webhook_events")
    op.drop_index(
        "uq_taxonomy_classification_jobs_active_scope_source_node",
        table_name="taxonomy_classification_jobs",
    )
    op.drop_table("taxonomy_classification_jobs")
    op.drop_index("uq_taxonomy_nodes_single_root", table_name="taxonomy_nodes")
    # ### end Alembic commands ###
