"""
Abstract: Alembic baseline for current API persistence schema.
Out of scope: Runtime API request handling and data backfills.

initial_api_schema

Revision ID: 11ab9b45e1eb
Revises:
Create Date: 2026-04-29 14:21:21.647884

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11ab9b45e1eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TAXONOMY_ASSIGNMENT_LEAF_FUNCTION = "enforce_node_taxonomy_assignment_leaf"
_TAXONOMY_ASSIGNMENT_LEAF_TRIGGER = "trg_node_taxonomy_assignments_leaf_only"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "ingestion_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_requests")),
    )
    op.create_index(
        "ix_ingestion_requests_idempotency_key_unique",
        "ingestion_requests",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("current_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(title, '')), 'A') || "
                "setweight(to_tsvector('english', coalesce(content, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("current_version >= 1", name=op.f("ck_nodes_current_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    op.create_index(
        "ix_nodes_search_vector", "nodes", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "taxonomy_classification_webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("queue_name", sa.Text(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.Column("terminal_state", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_classification_webhook_events")),
        sa.UniqueConstraint("event_id", name="uq_taxonomy_classification_webhook_events_event_id"),
    )
    op.create_index(
        "ix_taxonomy_classification_webhook_events_pending",
        "taxonomy_classification_webhook_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "taxonomy_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_leaf", sa.Boolean(), nullable=False),
        sa.CheckConstraint("depth >= 0", name=op.f("ck_taxonomy_nodes_depth_non_negative")),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_nodes_parent_id_taxonomy_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_nodes")),
        sa.UniqueConstraint("parent_id", "name", name="uq_taxonomy_nodes_parent_name"),
    )
    op.create_index(
        "uq_taxonomy_nodes_single_root",
        "taxonomy_nodes",
        [sa.literal_column("(COALESCE(parent_id, 0))")],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "card_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_card_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_card_versions_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_versions")),
        sa.UniqueConstraint("node_id", "version", name="uq_card_versions_node_version"),
    )
    op.create_index("ix_card_versions_node_id", "card_versions", ["node_id"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_a_id", sa.Integer(), nullable=False),
        sa.Column("node_b_id", sa.Integer(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("node_a_id < node_b_id", name=op.f("ck_edges_canonical_pair")),
        sa.CheckConstraint(
            "strength >= 0.0 AND strength <= 1.0", name=op.f("ck_edges_strength_range")
        ),
        sa.ForeignKeyConstraint(
            ["node_a_id"], ["nodes.id"], name=op.f("fk_edges_node_a_id_nodes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["node_b_id"], ["nodes.id"], name=op.f("fk_edges_node_b_id_nodes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edges")),
        sa.UniqueConstraint("node_a_id", "node_b_id", name="uq_edges_unordered_pair"),
    )
    op.create_table(
        "node_taxonomy_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("taxonomy_node_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_node_taxonomy_assignments_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_node_taxonomy_assignments_taxonomy_node_id_taxonomy_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_taxonomy_assignments")),
        sa.UniqueConstraint("node_id", name="uq_node_taxonomy_assignments_node_id"),
    )
    op.create_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id",
        "node_taxonomy_assignments",
        ["taxonomy_node_id"],
        unique=False,
    )
    op.create_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id_node_id",
        "node_taxonomy_assignments",
        ["taxonomy_node_id", "node_id"],
        unique=False,
    )
    op.execute(
        f"""
        CREATE FUNCTION {_TAXONOMY_ASSIGNMENT_LEAF_FUNCTION}()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM taxonomy_nodes
                WHERE id = NEW.taxonomy_node_id
                  AND is_leaf = TRUE
            ) THEN
                RAISE EXCEPTION
                    USING ERRCODE = '23514',
                          MESSAGE = (
                              'node_taxonomy_assignments.taxonomy_node_id '
                              'must reference a leaf taxonomy node'
                          );
            END IF;

            RETURN NEW;
        END;
        $$;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_TAXONOMY_ASSIGNMENT_LEAF_TRIGGER}
        BEFORE INSERT OR UPDATE OF taxonomy_node_id
        ON node_taxonomy_assignments
        FOR EACH ROW
        EXECUTE FUNCTION {_TAXONOMY_ASSIGNMENT_LEAF_FUNCTION}();
        """
    )
    op.create_table(
        "taxonomy_classification_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope_node_id", sa.Integer(), nullable=False),
        sa.Column("source_unclassified_node_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("terminal_state", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_payload", sa.JSON(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_taxonomy_classification_jobs_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_classification_jobs_scope_node_id_taxonomy_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["source_unclassified_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_classification_jobs_source_unclassified_node_id_taxonomy_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_classification_jobs")),
    )
    op.create_index(
        "uq_taxonomy_classification_jobs_active_scope_source_node",
        "taxonomy_classification_jobs",
        ["scope_node_id", "source_unclassified_node_id", "node_id"],
        unique=True,
        postgresql_where=sa.text("processed_at IS NULL AND terminal_state IS NULL"),
    )
    op.create_index(
        "uq_taxonomy_classification_jobs_job_id",
        "taxonomy_classification_jobs",
        ["job_id"],
        unique=True,
        postgresql_where=sa.text("job_id IS NOT NULL"),
    )
    op.create_table(
        "taxonomy_classification_webhook_wakeups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["taxonomy_classification_webhook_events.event_id"],
            name=op.f(
                "fk_taxonomy_classification_webhook_wakeups_event_id_taxonomy_classification_webhook_events"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_classification_webhook_wakeups")),
        sa.UniqueConstraint("event_id", name="uq_taxonomy_classification_webhook_wakeups_event_id"),
    )
    op.create_table(
        "adjacency",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("edge_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edge_id"], ["edges.id"], name=op.f("fk_adjacency_edge_id_edges"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_adjacency_node_id_nodes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("node_id", "edge_id", name=op.f("pk_adjacency")),
    )
    op.create_index("ix_adjacency_edge_id", "adjacency", ["edge_id"], unique=False)
    op.create_index("ix_adjacency_node_id", "adjacency", ["node_id"], unique=False)
    op.create_table(
        "card_suggested_edits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("suggested_title", sa.Text(), nullable=False),
        sa.Column("suggested_content", sa.Text(), nullable=False),
        sa.Column("suggested_by_user_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')",
            name=op.f("ck_card_suggested_edits_status"),
        ),
        sa.CheckConstraint(
            "base_version >= 1", name=op.f("ck_card_suggested_edits_base_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["node_id", "base_version"],
            ["card_versions.node_id", "card_versions.version"],
            name="fk_card_suggested_edits_base_version",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_suggested_edits")),
    )
    op.create_index(
        "ix_card_suggested_edits_node_id", "card_suggested_edits", ["node_id"], unique=False
    )
    op.create_index(
        "ix_card_suggested_edits_status", "card_suggested_edits", ["status"], unique=False
    )
    op.create_index(
        "ix_card_suggested_edits_suggested_by_user_id",
        "card_suggested_edits",
        ["suggested_by_user_id"],
        unique=False,
    )
    op.create_table(
        "taxonomy_leaf_projection_edges",
        sa.Column("leaf_id", sa.Integer(), nullable=False),
        sa.Column("edge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edges.id"],
            name=op.f("fk_taxonomy_leaf_projection_edges_edge_id_edges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["leaf_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_leaf_projection_edges_leaf_id_taxonomy_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "leaf_id", "edge_id", name=op.f("pk_taxonomy_leaf_projection_edges")
        ),
    )
    op.create_index(
        "ix_taxonomy_leaf_projection_edges_edge_id",
        "taxonomy_leaf_projection_edges",
        ["edge_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_taxonomy_leaf_projection_edges_edge_id", table_name="taxonomy_leaf_projection_edges"
    )
    op.drop_table("taxonomy_leaf_projection_edges")
    op.drop_index("ix_card_suggested_edits_suggested_by_user_id", table_name="card_suggested_edits")
    op.drop_index("ix_card_suggested_edits_status", table_name="card_suggested_edits")
    op.drop_index("ix_card_suggested_edits_node_id", table_name="card_suggested_edits")
    op.drop_table("card_suggested_edits")
    op.drop_index("ix_adjacency_node_id", table_name="adjacency")
    op.drop_index("ix_adjacency_edge_id", table_name="adjacency")
    op.drop_table("adjacency")
    op.drop_table("taxonomy_classification_webhook_wakeups")
    op.drop_index(
        "uq_taxonomy_classification_jobs_job_id",
        table_name="taxonomy_classification_jobs",
        postgresql_where=sa.text("job_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_taxonomy_classification_jobs_active_scope_source_node",
        table_name="taxonomy_classification_jobs",
        postgresql_where=sa.text("processed_at IS NULL AND terminal_state IS NULL"),
    )
    op.drop_table("taxonomy_classification_jobs")
    op.drop_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id_node_id",
        table_name="node_taxonomy_assignments",
    )
    op.drop_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id", table_name="node_taxonomy_assignments"
    )
    op.execute(
        f"""
        DROP TRIGGER IF EXISTS {_TAXONOMY_ASSIGNMENT_LEAF_TRIGGER}
        ON node_taxonomy_assignments;
        """
    )
    op.execute(f"DROP FUNCTION IF EXISTS {_TAXONOMY_ASSIGNMENT_LEAF_FUNCTION}();")
    op.drop_table("node_taxonomy_assignments")
    op.drop_table("edges")
    op.drop_index("ix_card_versions_node_id", table_name="card_versions")
    op.drop_table("card_versions")
    op.drop_index(
        "uq_taxonomy_nodes_single_root",
        table_name="taxonomy_nodes",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.drop_table("taxonomy_nodes")
    op.drop_index(
        "ix_taxonomy_classification_webhook_events_pending",
        table_name="taxonomy_classification_webhook_events",
    )
    op.drop_table("taxonomy_classification_webhook_events")
    op.drop_index("ix_nodes_search_vector", table_name="nodes", postgresql_using="gin")
    op.drop_table("nodes")
    op.drop_index(
        "ix_ingestion_requests_idempotency_key_unique",
        table_name="ingestion_requests",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_table("ingestion_requests")
    # ### end Alembic commands ###
