"""add_taxonomy_tables

Revision ID: 3e727ac5766a
Revises: 1155b96641f0
Create Date: 2026-04-05 00:36:19.306909

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e727ac5766a"
down_revision: str | Sequence[str] | None = "1155b96641f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_leaf", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "depth >= 0",
            name=op.f("ck_taxonomy_nodes_depth_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_nodes_parent_id_taxonomy_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_nodes")),
        sa.UniqueConstraint(
            "parent_id",
            "name",
            name="uq_taxonomy_nodes_parent_name",
        ),
    )
    op.create_table(
        "node_taxonomy_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("taxonomy_node_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_node_taxonomy_assignments_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_node_taxonomy_assignments_taxonomy_node_id_taxonomy_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_taxonomy_assignments")),
        sa.UniqueConstraint(
            "node_id",
            name="uq_node_taxonomy_assignments_node_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("node_taxonomy_assignments")
    op.drop_table("taxonomy_nodes")
    # ### end Alembic commands ###
