"""remove taxonomy view virtual unclassified

Revision ID: a06d96f5c69c
Revises: 43271e45f911
Create Date: 2026-05-07 03:37:09.662103

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a06d96f5c69c"
down_revision: str | Sequence[str] | None = "43271e45f911"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM taxonomy_scope_projection_edges WHERE scope_kind = 'virtual_unclassified'"
    )
    op.execute(
        "DELETE FROM taxonomy_card_scope_layout_compute_requests "
        "WHERE scope_kind = 'virtual_unclassified'"
    )
    op.execute("DELETE FROM taxonomy_card_scope_layouts WHERE scope_kind = 'virtual_unclassified'")
    op.drop_constraint(
        op.f("ck_taxonomy_card_scope_layout_compute_requests_scope_kind"),
        "taxonomy_card_scope_layout_compute_requests",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_taxonomy_card_scope_layout_compute_requests_scope_kind"),
        "taxonomy_card_scope_layout_compute_requests",
        "scope_kind IN ('taxonomy_node')",
    )
    op.drop_constraint(
        op.f("ck_taxonomy_card_scope_layouts_scope_kind"),
        "taxonomy_card_scope_layouts",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_taxonomy_card_scope_layouts_scope_kind"),
        "taxonomy_card_scope_layouts",
        "scope_kind IN ('taxonomy_node')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_taxonomy_card_scope_layouts_scope_kind"),
        "taxonomy_card_scope_layouts",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_taxonomy_card_scope_layouts_scope_kind"),
        "taxonomy_card_scope_layouts",
        "scope_kind IN ('taxonomy_node', 'virtual_unclassified')",
    )
    op.drop_constraint(
        op.f("ck_taxonomy_card_scope_layout_compute_requests_scope_kind"),
        "taxonomy_card_scope_layout_compute_requests",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_taxonomy_card_scope_layout_compute_requests_scope_kind"),
        "taxonomy_card_scope_layout_compute_requests",
        "scope_kind IN ('taxonomy_node', 'virtual_unclassified')",
    )
    # ### end Alembic commands ###
