"""add node search vector

Revision ID: af29da72fffb
Revises: a1b2c3d4e5f6
Create Date: 2026-04-29 13:40:59.360251

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af29da72fffb"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NODE_SEARCH_VECTOR_SQL = (
    "setweight(to_tsvector('english', coalesce(title, '')), 'A') || "
    "setweight(to_tsvector('english', coalesce(content, '')), 'B')"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nodes",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                NODE_SEARCH_VECTOR_SQL,
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_nodes_search_vector", "nodes", ["search_vector"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_nodes_search_vector", table_name="nodes", postgresql_using="gin")
    op.drop_column("nodes", "search_vector")
    # ### end Alembic commands ###
