"""semantic_map_tile_edges

Revision ID: 8fb221ce06d3
Revises: 892bf1e65619
Create Date: 2026-04-05 14:03:51.975158

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fb221ce06d3"
down_revision: str | Sequence[str] | None = "892bf1e65619"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "semantic_map_region_tiles",
        sa.Column("edge_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.alter_column("semantic_map_region_tiles", "edge_count", server_default=None)
    op.add_column(
        "semantic_map_region_tiles",
        sa.Column("edges", sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("semantic_map_region_tiles", "edges")
    op.drop_column("semantic_map_region_tiles", "edge_count")
    # ### end Alembic commands ###
