"""add taxonomy classification continuation requests

Revision ID: 95f3b4890da6
Revises: e781488adc12
Create Date: 2026-05-02 19:26:49.115340

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95f3b4890da6"
down_revision: str | Sequence[str] | None = "e781488adc12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy_classification_continuation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope_node_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("source_job_id", sa.Integer(), nullable=False),
        sa.Column("next_job_id", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["next_job_id"],
            ["taxonomy_classification_jobs.id"],
            name=op.f(
                "fk_taxonomy_classification_continuation_requests_next_job_id_taxonomy_classification_jobs"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_taxonomy_classification_continuation_requests_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f(
                "fk_taxonomy_classification_continuation_requests_scope_node_id_taxonomy_nodes"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"],
            ["taxonomy_classification_jobs.id"],
            name=op.f(
                "fk_taxonomy_classification_continuation_requests_source_job_id_taxonomy_classification_jobs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_taxonomy_classification_continuation_requests")
        ),
        sa.UniqueConstraint(
            "scope_node_id", "node_id", name="uq_taxonomy_classification_continuation_scope_node"
        ),
    )
    op.create_index(
        "ix_taxonomy_classification_continuation_updated_id",
        "taxonomy_classification_continuation_requests",
        ["updated_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_taxonomy_classification_continuation_updated_id",
        table_name="taxonomy_classification_continuation_requests",
    )
    op.drop_table("taxonomy_classification_continuation_requests")
    # ### end Alembic commands ###
