"""initial

Revision ID: df341c4118f3
Revises: 2a855fefebad
Create Date: 2026-04-03 02:40:46.723513

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df341c4118f3"
down_revision: str | Sequence[str] | None = "2a855fefebad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_a_id", sa.Integer(), nullable=False),
        sa.Column("node_b_id", sa.Integer(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.CheckConstraint("node_a_id < node_b_id", name=op.f("ck_edges_canonical_pair")),
        sa.CheckConstraint(
            "strength >= 0.0 AND strength <= 1.0", name=op.f("ck_edges_strength_range")
        ),
        sa.ForeignKeyConstraint(
            ["node_a_id"],
            ["nodes.id"],
            name=op.f("fk_edges_node_a_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_b_id"],
            ["nodes.id"],
            name=op.f("fk_edges_node_b_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edges")),
        sa.UniqueConstraint("node_a_id", "node_b_id", name="uq_edges_unordered_pair"),
    )
    op.create_table(
        "adjacency",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("edge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edges.id"],
            name=op.f("fk_adjacency_edge_id_edges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_adjacency_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("node_id", "edge_id", name=op.f("pk_adjacency")),
    )
    op.create_index("ix_adjacency_edge_id", "adjacency", ["edge_id"], unique=False)
    op.create_index("ix_adjacency_node_id", "adjacency", ["node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_adjacency_node_id", table_name="adjacency")
    op.drop_index("ix_adjacency_edge_id", table_name="adjacency")
    op.drop_table("adjacency")
    op.drop_table("edges")
    op.drop_table("nodes")
    # ### end Alembic commands ###
