"""add_nodes_embedding_hnsw_cosine_index

Revision ID: 43271e45f911
Revises: 2cb79ef5a6d1
Create Date: 2026-05-07 02:20:09.528775

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43271e45f911"
down_revision: str | Sequence[str] | None = "2cb79ef5a6d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_nodes_embedding_hnsw_cosine",
        "nodes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_nodes_embedding_hnsw_cosine",
        table_name="nodes",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    # ### end Alembic commands ###
