"""drop_semantic_map_tables

Revision ID: b3bac4c39e2e
Revises: a84d3d4ddb73
Create Date: 2026-04-07 00:15:23.100451

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3bac4c39e2e"
down_revision: str | Sequence[str] | None = "a84d3d4ddb73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("semantic_map_region_tiles")
    op.drop_index(
        op.f("uq_semantic_map_snapshots_current_true"),
        table_name="semantic_map_snapshots",
        postgresql_where="current",
    )
    op.drop_table("semantic_map_snapshots")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semantic_map_snapshots",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("version", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("schema_version", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "built_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("current", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "world_bounds",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tile_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("max_zoom", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "default_view",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("default_semantic_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "semantic_levels",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_map_snapshots")),
        sa.UniqueConstraint(
            "version",
            name=op.f("uq_semantic_map_snapshots_version"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("uq_semantic_map_snapshots_current_true"),
        "semantic_map_snapshots",
        ["current"],
        unique=True,
        postgresql_where="current",
    )
    op.create_table(
        "semantic_map_region_tiles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("semantic_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tile_z", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tile_x", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tile_y", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "tile_bounds",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("region_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("label_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "regions", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "labels", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "points",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("edge_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "edges",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["semantic_map_snapshots.id"],
            name=op.f("fk_semantic_map_region_tiles_snapshot_id_semantic_map_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_map_region_tiles")),
        sa.UniqueConstraint(
            "snapshot_id",
            "semantic_level",
            "tile_z",
            "tile_x",
            "tile_y",
            name=op.f("uq_semantic_map_region_tiles_snapshot_level_tile"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
