"""add leaf projection edge read model

Revision ID: 89c20cabf951
Revises: 49579adecef7
Create Date: 2026-04-09 15:19:08.961579

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89c20cabf951"
down_revision: str | Sequence[str] | None = "49579adecef7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy_leaf_projection_edges",
        sa.Column("leaf_id", sa.Integer(), nullable=False),
        sa.Column("edge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edges.id"],
            name=op.f("fk_taxonomy_leaf_projection_edges_edge_id_edges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["leaf_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_leaf_projection_edges_leaf_id_taxonomy_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "leaf_id", "edge_id", name=op.f("pk_taxonomy_leaf_projection_edges")
        ),
    )
    op.create_index(
        "ix_taxonomy_leaf_projection_edges_edge_id",
        "taxonomy_leaf_projection_edges",
        ["edge_id"],
        unique=False,
    )
    op.create_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id",
        "node_taxonomy_assignments",
        ["taxonomy_node_id"],
        unique=False,
    )
    op.create_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id_node_id",
        "node_taxonomy_assignments",
        ["taxonomy_node_id", "node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id_node_id",
        table_name="node_taxonomy_assignments",
    )
    op.drop_index(
        "ix_node_taxonomy_assignments_taxonomy_node_id", table_name="node_taxonomy_assignments"
    )
    op.drop_index(
        "ix_taxonomy_leaf_projection_edges_edge_id", table_name="taxonomy_leaf_projection_edges"
    )
    op.drop_table("taxonomy_leaf_projection_edges")
    # ### end Alembic commands ###
