"""add ingestion idempotency records

Revision ID: 7ced88ef1cab
Revises: 89c20cabf951
Create Date: 2026-04-24 11:43:36.473349

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ced88ef1cab"
down_revision: str | Sequence[str] | None = "89c20cabf951"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_idempotency_records",
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("ingestion_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("idempotency_key", name=op.f("pk_ingestion_idempotency_records")),
        sa.UniqueConstraint("ingestion_id", name="uq_ingestion_idempotency_records_ingestion_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingestion_idempotency_records")
    # ### end Alembic commands ###
