"""add taxonomy classification projection refresh requests

Revision ID: f3d2c1b0a9e8
Revises: 144fad053ee2
Create Date: 2026-05-01 16:40:55.991465

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3d2c1b0a9e8"
down_revision: str | Sequence[str] | None = "144fad053ee2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy_classification_projection_refresh_requests",
        sa.Column("leaf_id", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["leaf_id"],
            ["taxonomy_nodes.id"],
            name=op.f(
                "fk_taxonomy_classification_projection_refresh_requests_leaf_id_taxonomy_nodes"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "leaf_id", name=op.f("pk_taxonomy_classification_projection_refresh_requests")
        ),
    )
    op.create_index(
        "ix_tax_cls_proj_refresh_updated_at",
        "taxonomy_classification_projection_refresh_requests",
        ["updated_at", "leaf_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tax_cls_proj_refresh_updated_at",
        table_name="taxonomy_classification_projection_refresh_requests",
    )
    op.drop_table("taxonomy_classification_projection_refresh_requests")
    # ### end Alembic commands ###
