"""add_semantic_map_card_points_payload

Revision ID: 9a63ef3075bd
Revises: 8d54a8a2d1b4
Create Date: 2026-04-05 03:31:48.392231

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a63ef3075bd"
down_revision: str | Sequence[str] | None = "8d54a8a2d1b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "semantic_map_region_tiles",
        sa.Column("points", sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("semantic_map_region_tiles", "points")
    # ### end Alembic commands ###
