"""add card proposals

Revision ID: 77df962193b0
Revises: 95f3b4890da6
Create Date: 2026-05-03 23:20:21.769408

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77df962193b0"
down_revision: str | Sequence[str] | None = "95f3b4890da6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending_review'"), nullable=False),
        sa.Column("submitted_by_user_id", sa.Text(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Text(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "proposal_type IN ('create', 'edit', 'delete')",
            name=op.f("ck_card_proposals_proposal_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'accepted_applied', 'rejected', 'withdrawn')",
            name=op.f("ck_card_proposals_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_proposals")),
    )
    op.create_index(
        "ix_card_proposals_proposal_type", "card_proposals", ["proposal_type"], unique=False
    )
    op.create_index(
        "ix_card_proposals_reviewed_by_user_id",
        "card_proposals",
        ["reviewed_by_user_id"],
        unique=False,
    )
    op.create_index("ix_card_proposals_status", "card_proposals", ["status"], unique=False)
    op.create_index(
        "ix_card_proposals_submitted_by_user_id",
        "card_proposals",
        ["submitted_by_user_id"],
        unique=False,
    )
    op.create_table(
        "workspace_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("granted_by_user_id", sa.Text(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("revoked_by_user_id", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('reviewer', 'admin')", name=op.f("ck_workspace_roles_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_roles")),
    )
    op.create_index("ix_workspace_roles_role", "workspace_roles", ["role"], unique=False)
    op.create_index("ix_workspace_roles_user_id", "workspace_roles", ["user_id"], unique=False)
    op.create_index(
        "uq_workspace_roles_active_user_role",
        "workspace_roles",
        ["user_id", "role"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "proposal_apply_audits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_user_id", sa.Text(), nullable=False),
        sa.Column("proposal_type", sa.Text(), nullable=False),
        sa.Column("affected_node_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archive_outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["card_proposals.id"],
            name=op.f("fk_proposal_apply_audits_proposal_id_card_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_apply_audits")),
    )
    op.create_index(
        "ix_proposal_apply_audits_proposal_id",
        "proposal_apply_audits",
        ["proposal_id"],
        unique=False,
    )
    op.create_index(
        "ix_proposal_apply_audits_proposal_type",
        "proposal_apply_audits",
        ["proposal_type"],
        unique=False,
    )
    op.create_index(
        "ix_proposal_apply_audits_reviewer_user_id",
        "proposal_apply_audits",
        ["reviewer_user_id"],
        unique=False,
    )
    op.execute(
        """
        INSERT INTO card_proposals (
            id,
            proposal_type,
            status,
            submitted_by_user_id,
            reviewed_by_user_id,
            review_note,
            payload,
            created_at,
            updated_at,
            reviewed_at
        )
        SELECT
            id,
            'edit',
            CASE status
                WHEN 'accepted' THEN 'accepted_applied'
                WHEN 'rejected' THEN 'rejected'
                ELSE 'pending_review'
            END,
            suggested_by_user_id,
            NULL,
            NULL,
            jsonb_build_object(
                'target_node_id', node_id,
                'base_version', base_version,
                'suggested_title', suggested_title,
                'suggested_content', suggested_content
            ),
            created_at,
            updated_at,
            CASE
                WHEN status IN ('accepted', 'rejected') THEN updated_at
                ELSE NULL
            END
        FROM card_suggested_edits
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('card_proposals', 'id'),
            COALESCE((SELECT MAX(id) FROM card_proposals), 1),
            (SELECT COUNT(*) > 0 FROM card_proposals)
        )
        """
    )
    op.drop_index(op.f("ix_card_suggested_edits_node_id"), table_name="card_suggested_edits")
    op.drop_index(op.f("ix_card_suggested_edits_status"), table_name="card_suggested_edits")
    op.drop_index(
        op.f("ix_card_suggested_edits_suggested_by_user_id"), table_name="card_suggested_edits"
    )
    op.drop_table("card_suggested_edits")
    op.add_column(
        "nodes",
        sa.Column("lifecycle_state", sa.Text(), server_default=sa.text("'active'"), nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_nodes_lifecycle_state"),
        "nodes",
        "lifecycle_state IN ('active', 'archived')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_nodes_lifecycle_state"), "nodes", type_="check")
    op.drop_column("nodes", "lifecycle_state")
    op.create_table(
        "card_suggested_edits",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("node_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("base_version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("suggested_title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("suggested_content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("suggested_by_user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'pending'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])",
            name=op.f("ck_card_suggested_edits_status"),
        ),
        sa.CheckConstraint(
            "base_version >= 1", name=op.f("ck_card_suggested_edits_base_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["node_id", "base_version"],
            ["card_versions.node_id", "card_versions.version"],
            name=op.f("fk_card_suggested_edits_base_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_suggested_edits")),
    )
    op.execute(
        """
        INSERT INTO card_suggested_edits (
            id,
            node_id,
            base_version,
            suggested_title,
            suggested_content,
            suggested_by_user_id,
            status,
            created_at,
            updated_at
        )
        SELECT
            id,
            (payload ->> 'target_node_id')::integer,
            (payload ->> 'base_version')::integer,
            payload ->> 'suggested_title',
            payload ->> 'suggested_content',
            submitted_by_user_id,
            CASE status
                WHEN 'accepted_applied' THEN 'accepted'
                WHEN 'rejected' THEN 'rejected'
                ELSE 'pending'
            END,
            created_at,
            updated_at
        FROM card_proposals
        WHERE proposal_type = 'edit'
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('card_suggested_edits', 'id'),
            COALESCE((SELECT MAX(id) FROM card_suggested_edits), 1),
            (SELECT COUNT(*) > 0 FROM card_suggested_edits)
        )
        """
    )
    op.create_index(
        op.f("ix_card_suggested_edits_suggested_by_user_id"),
        "card_suggested_edits",
        ["suggested_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_card_suggested_edits_status"), "card_suggested_edits", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_card_suggested_edits_node_id"), "card_suggested_edits", ["node_id"], unique=False
    )
    op.drop_index("ix_proposal_apply_audits_reviewer_user_id", table_name="proposal_apply_audits")
    op.drop_index("ix_proposal_apply_audits_proposal_type", table_name="proposal_apply_audits")
    op.drop_index("ix_proposal_apply_audits_proposal_id", table_name="proposal_apply_audits")
    op.drop_table("proposal_apply_audits")
    op.drop_index(
        "uq_workspace_roles_active_user_role",
        table_name="workspace_roles",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_workspace_roles_user_id", table_name="workspace_roles")
    op.drop_index("ix_workspace_roles_role", table_name="workspace_roles")
    op.drop_table("workspace_roles")
    op.drop_index("ix_card_proposals_submitted_by_user_id", table_name="card_proposals")
    op.drop_index("ix_card_proposals_status", table_name="card_proposals")
    op.drop_index("ix_card_proposals_reviewed_by_user_id", table_name="card_proposals")
    op.drop_index("ix_card_proposals_proposal_type", table_name="card_proposals")
    op.drop_table("card_proposals")
    # ### end Alembic commands ###
