"""set_assignment_timestamp_db_default

Revision ID: a84d3d4ddb73
Revises: 8fb221ce06d3
Create Date: 2026-04-06 19:49:48.098166

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a84d3d4ddb73"
down_revision: str | Sequence[str] | None = "8fb221ce06d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_taxonomy_assignments",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_taxonomy_assignments",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
