"""add_semantic_map_snapshot_semantic_levels_payload

Revision ID: 892bf1e65619
Revises: 9a63ef3075bd
Create Date: 2026-04-05 04:14:28.708290

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "892bf1e65619"
down_revision: str | Sequence[str] | None = "9a63ef3075bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "semantic_map_snapshots",
        sa.Column(
            "semantic_levels",
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("semantic_map_snapshots", "semantic_levels")
    # ### end Alembic commands ###
