"""
Abstract: Enforce case-insensitive taxonomy sibling names.
Out of scope: Taxonomy import normalization and runtime assignment movement.

add taxonomy case insensitive sibling names

Revision ID: e11cee17761d
Revises: 11ab9b45e1eb
Create Date: 2026-04-30 11:27:27.768131

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e11cee17761d"
down_revision: str | Sequence[str] | None = "11ab9b45e1eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_taxonomy_nodes_parent_lower_name",
        "taxonomy_nodes",
        ["parent_id", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("parent_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_taxonomy_nodes_parent_lower_name",
        table_name="taxonomy_nodes",
        postgresql_where=sa.text("parent_id IS NOT NULL"),
    )
    # ### end Alembic commands ###
