"""add_semantic_map_snapshot_tables

Revision ID: 1155b96641f0
Revises: df341c4118f3
Create Date: 2026-04-03 14:47:03.766656

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1155b96641f0"
down_revision: str | Sequence[str] | None = "df341c4118f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semantic_map_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.Column("world_bounds", sa.JSON(), nullable=False),
        sa.Column("tile_size", sa.Integer(), nullable=False),
        sa.Column("max_zoom", sa.Integer(), nullable=False),
        sa.Column("default_view", sa.JSON(), nullable=False),
        sa.Column("default_semantic_level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_map_snapshots")),
        sa.UniqueConstraint("version", name="uq_semantic_map_snapshots_version"),
    )
    op.create_index(
        "uq_semantic_map_snapshots_current_true",
        "semantic_map_snapshots",
        ["current"],
        unique=True,
        postgresql_where=sa.text("current"),
    )
    op.create_table(
        "semantic_map_region_tiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("semantic_level", sa.Integer(), nullable=False),
        sa.Column("tile_z", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("tile_bounds", sa.JSON(), nullable=False),
        sa.Column("region_count", sa.Integer(), nullable=False),
        sa.Column("label_count", sa.Integer(), nullable=False),
        sa.Column("regions", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["semantic_map_snapshots.id"],
            name=op.f("fk_semantic_map_region_tiles_snapshot_id_semantic_map_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_map_region_tiles")),
        sa.UniqueConstraint(
            "snapshot_id",
            "semantic_level",
            "tile_z",
            "tile_x",
            "tile_y",
            name="uq_semantic_map_region_tiles_snapshot_level_tile",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("semantic_map_region_tiles")
    op.drop_index(
        "uq_semantic_map_snapshots_current_true",
        table_name="semantic_map_snapshots",
        postgresql_where=sa.text("current"),
    )
    op.drop_table("semantic_map_snapshots")
    # ### end Alembic commands ###
