"""taxonomy virtual unclassified hard cut

Revision ID: e781488adc12
Revises: f3d2c1b0a9e8
Create Date: 2026-05-02 14:48:22.724775

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e781488adc12"
down_revision: str | Sequence[str] | None = "f3d2c1b0a9e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TAXONOMY_ASSIGNMENT_LEAF_FUNCTION = "enforce_node_taxonomy_assignment_leaf"
_TAXONOMY_ASSIGNMENT_LEAF_TRIGGER = "trg_node_taxonomy_assignments_leaf_only"


def upgrade() -> None:
    """Upgrade schema."""
    _assert_no_active_taxonomy_classification_jobs()
    _drop_leaf_assignment_trigger()
    _clear_derived_projection_refresh_requests()
    _promote_legacy_unclassified_assignments()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy_scope_projection_edges",
        sa.Column("scope_kind", sa.Text(), nullable=False),
        sa.Column("taxonomy_node_id", sa.Integer(), nullable=False),
        sa.Column("edge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edges.id"],
            name=op.f("fk_taxonomy_scope_projection_edges_edge_id_edges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_scope_projection_edges_taxonomy_node_id_taxonomy_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "scope_kind",
            "taxonomy_node_id",
            "edge_id",
            name=op.f("pk_taxonomy_scope_projection_edges"),
        ),
    )
    op.create_index(
        "ix_taxonomy_scope_projection_edges_edge_id",
        "taxonomy_scope_projection_edges",
        ["edge_id"],
        unique=False,
    )
    op.create_index(
        "ix_taxonomy_scope_projection_edges_scope",
        "taxonomy_scope_projection_edges",
        ["scope_kind", "taxonomy_node_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_taxonomy_leaf_projection_edges_edge_id"),
        table_name="taxonomy_leaf_projection_edges",
    )
    op.drop_table("taxonomy_leaf_projection_edges")
    op.drop_index(
        op.f("uq_taxonomy_classification_jobs_active_scope_source_node"),
        table_name="taxonomy_classification_jobs",
        postgresql_where="((processed_at IS NULL) AND (terminal_state IS NULL))",
    )
    op.create_index(
        "uq_taxonomy_classification_jobs_active_scope_node",
        "taxonomy_classification_jobs",
        ["scope_node_id", "node_id"],
        unique=True,
        postgresql_where=sa.text("processed_at IS NULL AND terminal_state IS NULL"),
    )
    op.drop_constraint(
        op.f("fk_taxonomy_classification_jobs_source_unclassified_nod_9d9e"),
        "taxonomy_classification_jobs",
        type_="foreignkey",
    )
    op.drop_column("taxonomy_classification_jobs", "source_unclassified_node_id")
    _delete_legacy_unclassified_taxonomy_nodes()
    op.add_column(
        "taxonomy_classification_projection_refresh_requests",
        sa.Column("scope_kind", sa.Text(), nullable=False),
    )
    op.add_column(
        "taxonomy_classification_projection_refresh_requests",
        sa.Column("taxonomy_node_id", sa.Integer(), nullable=False),
    )
    op.drop_index(
        op.f("ix_tax_cls_proj_refresh_updated_at"),
        table_name="taxonomy_classification_projection_refresh_requests",
    )
    op.create_index(
        "ix_tax_cls_proj_refresh_updated_at",
        "taxonomy_classification_projection_refresh_requests",
        ["updated_at", "scope_kind", "taxonomy_node_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_taxonomy_classification_projection_refresh_requests__f224"),
        "taxonomy_classification_projection_refresh_requests",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f(
            "fk_taxonomy_classification_projection_refresh_requests_taxonomy_node_id_taxonomy_nodes"
        ),
        "taxonomy_classification_projection_refresh_requests",
        "taxonomy_nodes",
        ["taxonomy_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("pk_taxonomy_classification_projection_refresh_requests"),
        "taxonomy_classification_projection_refresh_requests",
        type_="primary",
    )
    op.create_primary_key(
        op.f("pk_taxonomy_classification_projection_refresh_requests"),
        "taxonomy_classification_projection_refresh_requests",
        ["scope_kind", "taxonomy_node_id"],
    )
    op.drop_column("taxonomy_classification_projection_refresh_requests", "leaf_id")
    op.drop_column("taxonomy_nodes", "is_leaf")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "taxonomy_nodes", sa.Column("is_leaf", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "taxonomy_classification_projection_refresh_requests",
        sa.Column("leaf_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f(
            "fk_taxonomy_classification_projection_refresh_requests_taxonomy_node_id_taxonomy_nodes"
        ),
        "taxonomy_classification_projection_refresh_requests",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_taxonomy_classification_projection_refresh_requests__f224"),
        "taxonomy_classification_projection_refresh_requests",
        "taxonomy_nodes",
        ["leaf_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "ix_tax_cls_proj_refresh_updated_at",
        table_name="taxonomy_classification_projection_refresh_requests",
    )
    op.create_index(
        op.f("ix_tax_cls_proj_refresh_updated_at"),
        "taxonomy_classification_projection_refresh_requests",
        ["updated_at", "leaf_id"],
        unique=False,
    )
    op.drop_column("taxonomy_classification_projection_refresh_requests", "taxonomy_node_id")
    op.drop_column("taxonomy_classification_projection_refresh_requests", "scope_kind")
    op.add_column(
        "taxonomy_classification_jobs",
        sa.Column("source_unclassified_node_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_taxonomy_classification_jobs_source_unclassified_nod_9d9e"),
        "taxonomy_classification_jobs",
        "taxonomy_nodes",
        ["source_unclassified_node_id"],
        ["id"],
    )
    op.drop_index(
        "uq_taxonomy_classification_jobs_active_scope_node",
        table_name="taxonomy_classification_jobs",
        postgresql_where=sa.text("processed_at IS NULL AND terminal_state IS NULL"),
    )
    op.create_index(
        op.f("uq_taxonomy_classification_jobs_active_scope_source_node"),
        "taxonomy_classification_jobs",
        ["scope_node_id", "source_unclassified_node_id", "node_id"],
        unique=True,
        postgresql_where="((processed_at IS NULL) AND (terminal_state IS NULL))",
    )
    op.create_table(
        "taxonomy_leaf_projection_edges",
        sa.Column("leaf_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("edge_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edges.id"],
            name=op.f("fk_taxonomy_leaf_projection_edges_edge_id_edges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["leaf_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_leaf_projection_edges_leaf_id_taxonomy_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "leaf_id", "edge_id", name=op.f("pk_taxonomy_leaf_projection_edges")
        ),
    )
    op.create_index(
        op.f("ix_taxonomy_leaf_projection_edges_edge_id"),
        "taxonomy_leaf_projection_edges",
        ["edge_id"],
        unique=False,
    )
    op.drop_index(
        "ix_taxonomy_scope_projection_edges_scope", table_name="taxonomy_scope_projection_edges"
    )
    op.drop_index(
        "ix_taxonomy_scope_projection_edges_edge_id", table_name="taxonomy_scope_projection_edges"
    )
    op.drop_table("taxonomy_scope_projection_edges")
    # ### end Alembic commands ###


def _assert_no_active_taxonomy_classification_jobs() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM taxonomy_classification_jobs
                WHERE processed_at IS NULL
                  AND terminal_state IS NULL
            ) THEN
                RAISE EXCEPTION
                    USING ERRCODE = '55000',
                          MESSAGE = (
                              'taxonomy virtual unclassified migration requires '
                              'zero active taxonomy classification jobs'
                          );
            END IF;
        END;
        $$;
        """
    )


def _drop_leaf_assignment_trigger() -> None:
    op.execute(
        f"""
        DROP TRIGGER IF EXISTS {_TAXONOMY_ASSIGNMENT_LEAF_TRIGGER}
        ON node_taxonomy_assignments;
        """
    )
    op.execute(f"DROP FUNCTION IF EXISTS {_TAXONOMY_ASSIGNMENT_LEAF_FUNCTION}();")


def _clear_derived_projection_refresh_requests() -> None:
    op.execute("DELETE FROM taxonomy_classification_projection_refresh_requests;")


def _promote_legacy_unclassified_assignments() -> None:
    op.execute(
        """
        UPDATE node_taxonomy_assignments AS assignment
           SET taxonomy_node_id = parent.id
          FROM taxonomy_nodes AS legacy_unclassified
          JOIN taxonomy_nodes AS parent
            ON parent.id = legacy_unclassified.parent_id
         WHERE assignment.taxonomy_node_id = legacy_unclassified.id
           AND legacy_unclassified.name = 'Unclassified';
        """
    )


def _delete_legacy_unclassified_taxonomy_nodes() -> None:
    op.execute("DELETE FROM taxonomy_nodes WHERE name = 'Unclassified';")
