"""initial_wikipedia_schema

Revision ID: 7819fd803075
Revises:
Create Date: 2026-04-05 02:28:08.113714

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7819fd803075"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    search_vector_sql = (
        "setweight(to_tsvector('english', coalesce(title, '')), 'A') || "
        "setweight(to_tsvector('english', coalesce(clean_text, '')), 'B')"
    )

    op.create_table(
        "documents",
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("clean_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(search_vector_sql, persisted=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("page_id", name=op.f("pk_documents")),
        schema="wikipedia",
    )
    op.create_index(
        "ix_wikipedia_documents_search_vector",
        "documents",
        ["search_vector"],
        unique=False,
        schema="wikipedia",
        postgresql_using="gin",
    )
    op.create_table(
        "processed_documents",
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("external_target_ref", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["wikipedia.documents.page_id"],
            name=op.f("fk_processed_documents_page_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("page_id", name=op.f("pk_processed_documents")),
        schema="wikipedia",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_documents", schema="wikipedia")
    op.drop_index(
        "ix_wikipedia_documents_search_vector",
        table_name="documents",
        schema="wikipedia",
        postgresql_using="gin",
    )
    op.drop_table("documents", schema="wikipedia")
    # ### end Alembic commands ###
